/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAnalyzeRouteImport } from './routes/api/analyze'
import { Route as ApiFetchSourceRouteImport } from './routes/api/fetch-source'
import { Route as ApiTranslateRouteImport } from './routes/api/translate'
import { Route as ApiTutorRouteImport } from './routes/api/tutor'
import { Route as SessionSessionIdRouteImport } from './routes/session.$sessionId'
import { Route as SourceSourceIdRouteImport } from './routes/source.$sourceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeRoute = ApiAnalyzeRouteImport.update({
  id: '/api/analyze',
  path: '/api/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFetchSourceRoute = ApiFetchSourceRouteImport.update({
  id: '/api/fetch-source',
  path: '/api/fetch-source',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranslateRoute = ApiTranslateRouteImport.update({
  id: '/api/translate',
  path: '/api/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTutorRoute = ApiTutorRouteImport.update({
  id: '/api/tutor',
  path: '/api/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdRoute = SessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceSourceIdRoute = SourceSourceIdRouteImport.update({
  id: '/source/$sourceId',
  path: '/source/$sourceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/fetch-source': typeof ApiFetchSourceRoute
  '/api/translate': typeof ApiTranslateRoute
  '/api/tutor': typeof ApiTutorRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/source/$sourceId': typeof SourceSourceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/fetch-source': typeof ApiFetchSourceRoute
  '/api/translate': typeof ApiTranslateRoute
  '/api/tutor': typeof ApiTutorRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/source/$sourceId': typeof SourceSourceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/fetch-source': typeof ApiFetchSourceRoute
  '/api/translate': typeof ApiTranslateRoute
  '/api/tutor': typeof ApiTutorRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/source/$sourceId': typeof SourceSourceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/analyze'
    | '/api/fetch-source'
    | '/api/translate'
    | '/api/tutor'
    | '/session/$sessionId'
    | '/source/$sourceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/analyze'
    | '/api/fetch-source'
    | '/api/translate'
    | '/api/tutor'
    | '/session/$sessionId'
    | '/source/$sourceId'
  id:
    | '__root__'
    | '/'
    | '/api/analyze'
    | '/api/fetch-source'
    | '/api/translate'
    | '/api/tutor'
    | '/session/$sessionId'
    | '/source/$sourceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAnalyzeRoute: typeof ApiAnalyzeRoute
  ApiFetchSourceRoute: typeof ApiFetchSourceRoute
  ApiTranslateRoute: typeof ApiTranslateRoute
  ApiTutorRoute: typeof ApiTutorRoute
  SessionSessionIdRoute: typeof SessionSessionIdRoute
  SourceSourceIdRoute: typeof SourceSourceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze': {
      id: '/api/analyze'
      path: '/api/analyze'
      fullPath: '/api/analyze'
      preLoaderRoute: typeof ApiAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fetch-source': {
      id: '/api/fetch-source'
      path: '/api/fetch-source'
      fullPath: '/api/fetch-source'
      preLoaderRoute: typeof ApiFetchSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/translate': {
      id: '/api/translate'
      path: '/api/translate'
      fullPath: '/api/translate'
      preLoaderRoute: typeof ApiTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tutor': {
      id: '/api/tutor'
      path: '/api/tutor'
      fullPath: '/api/tutor'
      preLoaderRoute: typeof ApiTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId': {
      id: '/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/source/$sourceId': {
      id: '/source/$sourceId'
      path: '/source/$sourceId'
      fullPath: '/source/$sourceId'
      preLoaderRoute: typeof SourceSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAnalyzeRoute: ApiAnalyzeRoute,
  ApiFetchSourceRoute: ApiFetchSourceRoute,
  ApiTranslateRoute: ApiTranslateRoute,
  ApiTutorRoute: ApiTutorRoute,
  SessionSessionIdRoute: SessionSessionIdRoute,
  SourceSourceIdRoute: SourceSourceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
